package enums;

public enum Endpoint {
    UNKNOWN,
    TASK_GET_FULL_LIST,
    TASK_SEARCH,
    TASK_CREATE_UPDATE,
    TASK_DELETE,
    SUBTASK_GET_FULL_LIST,
    SUBTASK_SEARCH,
    SUBTASK_CREATE_UPDATE,
    SUBTASK_DELETE,
    EPIC_GET_FULL_LIST,
    EPIC_SEARCH,
    EPIC_GET_SUBTASKS_LIST,
    EPIC_CREATE,
    EPIC_DELETE,
    HISTORY_GET_LIST,
    PRIORITIZED_GET_LIST
}
